### ISSUE TITLE
Añadir puntos a los números

### ISSUE THREAD

**Issue by jesusjimsa** [jesusjimsa/COVID-19-Data-Twitter-Spain#10]
Los números de diferencias en las vacunaciones no se están publicando con los puntos y es lioso comprobar cuántas vacunas nuevas se han puesto. Por ejemplo, en lugar de enviar `+23.456` se está enviando `+23456`. No está mal, pero los puntos ayudarían a leer las diferencias.
Estos números se obtienen de `yesterday.txt` y los datos del día, está regular pensado, así que habría que darle una vuelta para obtener estos números de mejor forma.
Se obtienen aquí:
https://github.com/jesusjimsa/COVID-19-Data-Twitter-Spain/blob/e1de971c78bbf6b0c62cc32f9d6bf42c67e228b4/covid.py#L62-L93

**Comment by callapa1** [comment]
teniendo en cuenta que 
```php
>>> num = 10000000
>>> print(f"{num:,}")
10,000,000
```
y para no modificar el string antes del calculo, se puede tomar cada string final (por ejemplo `diff_cases_str`) y modifiarlo, quedando así:
```php
diff_distribuidas_str = '+' + str(diff_distribuidas) if diff_distribuidas >= 0 else str(diff_distribuidas)
diff_administradas_str = '+' + str(diff_administradas) if diff_administradas >= 0 else str(diff_administradas)
diff_completas_str = '+' + str(diff_completas) if diff_completas >= 0 else str(diff_completas)

def dot_in_string(value):
	if value != '0':
		if isinstance(txt[0], int):
			value = '{:,}'.format(int(value)).replace(',', '.')
		else:
			value = value[0] + '{:,}'.format(int(value[1:])).replace(',', '.')
	return value

diff_distribuidas_str = dot_in_string(diff_distribuidas_str)
diff_administradas_str = dot_in_string(diff_administradas_str)
diff_completas_str = dot_in_string(diff_completas_str)
```

(la funcion debería ir con las demás)

**Comment by jesusjimsa** [comment]
Hola, @callapa1.

Es buena idea, en cuanto tenga algo de tiempo para volver a ponerme con el bot lo implementaré.
También, si quieres, estás invitado a abrir pull request. :slightly_smiling_face::octocat:
